# Generated by Django 3.2.12 on 2023-07-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20230713_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='detail',
        ),
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BusinessDetail',
        ),
    ]
