# Generated by Django 3.2.12 on 2023-08-25 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20230725_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='user',
            new_name='admin',
        ),
    ]
