# Generated by Django 3.2.12 on 2023-12-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_business_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='phone_number',
            field=models.CharField(blank=True, default=123456789, max_length=11, verbose_name='شماره تماس'),
            preserve_default=False,
        ),
    ]
