# Generated by Django 3.2.12 on 2024-01-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_business_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=256, verbose_name='اسلاگ'),
        ),
    ]
