# Generated by Django 3.2.12 on 2024-03-23 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0007_alter_business_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=24)),
                ('description', models.CharField(max_length=512)),
                ('field', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'درخواست همکاری',
                'verbose_name_plural': 'درخواست های همکاری',
            },
        ),
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField(verbose_name='تاریخ درخواست شده')),
                ('requested_price', models.IntegerField(verbose_name='مبلغ درخواست')),
                ('status', models.IntegerField(blank=True, choices=[('درحال انتظار', 0), ('تسویه شده', 1), ('رد شده', 2)], default=0, null=True, verbose_name='وضعیت')),
                ('deposit_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تسویه')),
                ('document', models.ImageField(blank=True, null=True, upload_to='', verbose_name='مستندات تسویه')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ارسال کننده')),
            ],
            options={
                'verbose_name': 'درخواست تسویه',
                'verbose_name_plural': 'درخواست های تسویه',
                'ordering': ['-requested_date'],
            },
        ),
    ]
