# Generated by Django 3.2.12 on 2024-04-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_corporaterequest_depositrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='lang_map',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True, verbose_name='طول موقعیت مکانی'),
        ),
        migrations.AddField(
            model_name='business',
            name='lat_map',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True, verbose_name='عرض موقعیت مکانی'),
        ),
    ]
