# Generated by Django 3.2.12 on 2024-04-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20240417_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='lang_map',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='طول موقعیت مکانی'),
        ),
        migrations.AlterField(
            model_name='business',
            name='lat_map',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='عرض موقعیت مکانی'),
        ),
    ]
