# Generated by Django 3.2.12 on 2025-02-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_auto_20240426_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='lang_map',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=18, null=True, verbose_name='طول موقعیت مکانی'),
        ),
        migrations.AlterField(
            model_name='business',
            name='lat_map',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=18, null=True, verbose_name='عرض موقعیت مکانی'),
        ),
        migrations.AlterField(
            model_name='corporaterequest',
            name='description',
            field=models.CharField(max_length=512, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='corporaterequest',
            name='field',
            field=models.CharField(max_length=255, verbose_name='زمینه کاری'),
        ),
        migrations.AlterField(
            model_name='corporaterequest',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='corporaterequest',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='corporaterequest',
            name='phone_number',
            field=models.CharField(max_length=24, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'درحال انتظار'), (1, 'تسویه شده'), (2, 'رد شده')], default=0, null=True, verbose_name='وضعیت'),
        ),
    ]
