# Generated by Django 3.2.12 on 2023-07-11 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_alter_business_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=256)),
                ('level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=2)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coupon.category')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('terms_of_use', models.TextField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
                ('category', models.ManyToManyField(to='coupon.Category')),
            ],
        ),
        migrations.CreateModel(
            name='LineCouponDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=16)),
                ('discount_percent', models.CharField(default=0, max_length=8)),
                ('sell_count', models.CharField(default=0, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='LineCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('is_main', models.BooleanField(default=False)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon')),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coupon.linecoupondetail')),
            ],
        ),
    ]
