# Generated by Django 3.2.12 on 2023-09-04 22:54

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=256)),
                ('level', models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coupon.category')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expire_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 15, 2, 24, 54, 980006))),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('terms_of_use', models.TextField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
                ('category', models.ManyToManyField(to='coupon.Category')),
            ],
        ),
        migrations.CreateModel(
            name='LineCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('is_main', models.BooleanField(default=False)),
                ('count', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('offer_percent', models.PositiveSmallIntegerField()),
                ('price_with_offer', models.PositiveIntegerField(blank=True, null=True)),
                ('sell_count', models.PositiveIntegerField(blank=True, default=0)),
                ('rate', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.category')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
    ]
