# Generated by Django 3.2.12 on 2023-07-11 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='slug',
        ),
    ]
