# Generated by Django 3.2.12 on 2023-07-09 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_title'),
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='business.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linecoupon',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
