# Generated by Django 3.2.12 on 2023-07-09 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_auto_20230709_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('level', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1, max_length=2)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coupon.category')),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='category',
            field=models.ManyToManyField(to='coupon.Category'),
        ),
    ]
