# Generated by Django 3.2.12 on 2023-07-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_remove_coupon_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=256),
        ),
    ]
