# Generated by Django 3.2.12 on 2023-09-04 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_alter_coupon_expire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linecoupon',
            old_name='final_price',
            new_name='price_with_offer',
        ),
        migrations.RenameField(
            model_name='linecoupon',
            old_name='bought_count',
            new_name='sell_count',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 14, 13, 9, 11, 823926)),
        ),
    ]
