# Generated by Django 3.2.12 on 2023-09-10 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linecoupon',
            name='rate',
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_rate',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='coupon',
            name='rate_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
