# Generated by Django 3.2.12 on 2023-09-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_auto_20230910_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
