# Generated by Django 3.2.12 on 2023-09-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0007_auto_20230910_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
