# Generated by Django 3.2.12 on 2023-08-24 11:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0007_alter_coupon_expire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linecoupon',
            name='detail',
        ),
        migrations.AddField(
            model_name='linecoupon',
            name='discount_percent',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='linecoupon',
            name='price',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linecoupon',
            name='sell_count',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 11, 52, 19, 180693, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='LineCouponDetail',
        ),
    ]
