# Generated by Django 3.2.12 on 2023-08-27 00:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0008_auto_20230824_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 0, 33, 4, 891790, tzinfo=utc)),
        ),
    ]
