# Generated by Django 3.2.12 on 2023-08-27 00:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0010_auto_20230827_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 0, 37, 23, 463782, tzinfo=utc)),
        ),
    ]
