# Generated by Django 3.2.12 on 2023-11-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0010_auto_20230911_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
    ]
