# Generated by Django 3.2.12 on 2023-10-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0010_auto_20230911_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
