# Generated by Django 3.2.12 on 2023-08-27 00:48

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0011_alter_coupon_expire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linecoupon',
            name='sell_count',
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 0, 48, 37, 563624, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='linecoupon',
            name='discount_percent',
            field=models.SmallIntegerField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='linecoupon',
            name='price',
            field=models.IntegerField(),
        ),
    ]
