# Generated by Django 3.2.12 on 2023-10-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0011_coupon_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.CharField(blank=True, choices=[('created', 'ایجاد شده'), ('confirmed', 'تایید شده'), ('rejected', 'رد شده')], max_length=50, null=True),
        ),
    ]
