# Generated by Django 3.2.12 on 2023-08-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0012_auto_20230827_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
