# Generated by Django 3.2.12 on 2023-11-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0012_auto_20231113_1854'),
        ('coupon', '0012_comment_verified'),
        ('coupon', '0012_couponimage'),
    ]

    operations = [
    ]
