# Generated by Django 3.2.12 on 2023-11-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0013_merge_20231115_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, null=True, verbose_name='امتیاز کوپن'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='rate_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='تعداد رای دهندگان'),
        ),
    ]
