# Generated by Django 3.2.12 on 2023-08-27 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0015_alter_coupon_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linecoupon',
            name='discount_percent',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='linecoupon',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
