# Generated by Django 3.2.12 on 2024-01-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0016_alter_rate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
    ]
