# Generated by Django 3.2.12 on 2024-01-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0018_auto_20240114_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=256, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=256, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='linecoupon',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
