# Generated by Django 3.2.12 on 2023-08-28 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0019_auto_20230827_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 7, 13, 33, 2, 878886)),
        ),
    ]
