# Generated by Django 3.2.12 on 2024-01-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0019_auto_20240117_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, verbose_name='امتیاز کوپن'),
        ),
        migrations.AlterField(
            model_name='linecoupon',
            name='offer_percent',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='درصد تخفیف'),
        ),
    ]
