# Generated by Django 3.2.12 on 2024-02-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0020_auto_20240117_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='linecoupon',
            name='commission',
            field=models.PositiveIntegerField(default=0, verbose_name='پورسانت'),
        ),
    ]
