# Generated by Django 3.2.12 on 2024-03-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0021_linecoupon_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='active_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ فعال سازی'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='فعال/غیرفعال'),
        ),
    ]
