# Generated by Django 3.2.12 on 2023-08-28 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0021_auto_20230828_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 8, 2, 44, 52, 687791)),
        ),
    ]
