# Generated by Django 3.2.12 on 2024-06-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0022_auto_20240323_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, max_length=104857600, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='terms_of_use',
            field=models.TextField(blank=True, max_length=104857600, null=True, verbose_name='شرایط استفاده'),
        ),
    ]
