# Generated by Django 3.2.12 on 2025-02-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0023_auto_20240625_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='special_order',
            field=models.SmallIntegerField(blank=True, default=-1, verbose_name='ترتیب در شگفت انگیزان'),
        ),
    ]
