# Generated by Django 3.2.12 on 2023-08-30 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0023_auto_20230830_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 9, 5, 35, 54, 117394)),
        ),
    ]
