# Generated by Django 3.2.12 on 2023-08-30 02:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0026_alter_coupon_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='linecoupon',
            name='bought_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='linecoupon',
            name='count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linecoupon',
            name='rate',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 9, 5, 47, 29, 673414)),
        ),
    ]
