<<<<<<< HEAD
# Generated by Django 3.2.12 on 2023-08-31 00:31
=======
# Generated by Django 3.2.12 on 2023-09-01 10:43
>>>>>>> ab684cbfc0d95d589b30bf722f83cdf8a18d32b2

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('coupon', '0028_auto_20230831_0400'),
=======
        ('coupon', '0028_alter_coupon_expire_date'),
>>>>>>> ab684cbfc0d95d589b30bf722f83cdf8a18d32b2
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
<<<<<<< HEAD
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 10, 4, 1, 32, 656973)),
=======
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 11, 14, 13, 23, 406850)),
>>>>>>> ab684cbfc0d95d589b30bf722f83cdf8a18d32b2
        ),
    ]
