# Generated by Django 3.2.12 on 2023-08-31 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0028_auto_20230831_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 10, 4, 1, 32, 656973)),
        ),
    ]
