# Generated by Django 3.2.12 on 2023-10-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='is_slider',
            field=models.BooleanField(default=True, verbose_name='بنر هست / نیست'),
            preserve_default=False,
        ),
    ]
