# Generated by Django 3.2.12 on 2023-11-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0002_advertise_is_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertise',
            options={'verbose_name': 'تبلیغات', 'verbose_name_plural': 'تبلیغات'},
        ),
        migrations.AddField(
            model_name='advertise',
            name='title',
            field=models.CharField(default=1, max_length=128, verbose_name='عنوان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertise',
            name='file',
            field=models.FileField(upload_to='advertise/', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='link',
            field=models.URLField(verbose_name='لینک'),
        ),
    ]
