# Generated by Django 3.2.12 on 2023-11-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0002_advertise_is_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='is_slider',
            field=models.BooleanField(default=True, verbose_name='بنر هست / نیست'),
        ),
    ]
