# Generated by Django 3.2.12 on 2023-11-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0003_alter_advertise_is_slider'),
        ('advertise', '0003_auto_20231111_2207'),
    ]

    operations = [
    ]
