# Generated by Django 3.2.12 on 2023-11-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0004_merge_20231115_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='is_slider',
            field=models.BooleanField(verbose_name='بنر هست / نیست'),
        ),
    ]
