# Generated by Django 3.2.12 on 2023-11-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231110_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sms_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
