# Generated by Django 3.2.12 on 2023-11-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='آدرس'),
        ),
    ]
