# Generated by Django 3.2.12 on 2023-11-10 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('gateway', models.CharField(choices=[('BMI', 'ملی'), ('SEP', 'SEP'), ('ZARINPAL', 'زرین پال'), ('IDPAY', 'آیدی پی'), ('MELLAT', 'ملت'), ('ZIBAL', 'زیبال'), ('BAHAMTA', 'با همتا'), ('PAYV1', 'PAYV1')], max_length=10)),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Gateway',
                'verbose_name_plural': 'Gateways',
            },
        ),
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'جدید'), (2, 'انتظار'), (3, 'موفق'), (4, 'ناموفق'), (5, 'لغو')], default=1, verbose_name='وضعیت')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='توکن')),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('response', models.JSONField(blank=True, default=dict, null=True)),
                ('ref_id', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('paid_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_gateway.gateway')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket.basket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Online Payment',
                'verbose_name_plural': 'Online Payments',
            },
        ),
    ]
