# Generated by Django 3.2.12 on 2023-10-21 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0007_rename_closed_basket_payment_basket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(1, 'زرین پال'), (1, 'درگاه های دیگر')])),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('active', models.BooleanField(default=True)),
                ('logo', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='لوگو')),
            ],
            options={
                'verbose_name': 'Gateway',
                'verbose_name_plural': 'Gateways',
            },
        ),
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'جدید'), (2, 'انتظار'), (3, 'موفق'), (4, 'ناموفق'), (5, 'لغو')], default=1, verbose_name='وضعیت')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='توکن')),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('response', models.JSONField(blank=True, default=dict, null=True)),
                ('ref_id', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('failed_code', models.IntegerField(choices=[(0, 'بدون خطا'), (5, 'خطای انتقال به درگاه پرداخت'), (10, 'خطای پرداخت در درگاه'), (15, 'خطای اعتبار سنجی پرداخت'), (20, 'خطای ارتباط با درگاه پرداخت'), (30, 'خطای نهایی سازی پرداخت')], default=0)),
                ('failed_cause', models.CharField(default='', max_length=255)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_gateway.gateway')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Online Payment',
                'verbose_name_plural': 'Online Payments',
            },
        ),
    ]
