# Generated by Django 3.2.12 on 2023-11-13 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_auto_20231113_1854'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gateway',
            options={'verbose_name': 'درگاه پرداخت', 'verbose_name_plural': 'درگاه های پرداخت'},
        ),
        migrations.AlterModelOptions(
            name='onlinepayment',
            options={'verbose_name': 'پرداخت های آنلاین', 'verbose_name_plural': 'پرداخت های آنلاین'},
        ),
        migrations.AlterField(
            model_name='gateway',
            name='active',
            field=models.BooleanField(default=False, verbose_name='فعال / غیرفعال'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='اطلاعات درگاه مانند مرچنت آیدی و ... را در این قسمت قرار دهید!', null=True, verbose_name='اطلاعات درگاه'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='gateway',
            field=models.CharField(choices=[('BMI', 'ملی'), ('SEP', 'SEP'), ('ZARINPAL', 'زرین پال'), ('IDPAY', 'آیدی پی'), ('MELLAT', 'ملت'), ('ZIBAL', 'زیبال'), ('BAHAMTA', 'با همتا'), ('PAYV1', 'PAYV1')], max_length=10, verbose_name='نوع درگاه'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='name',
            field=models.CharField(max_length=128, verbose_name='نام درگاه'),
        ),
        migrations.AlterField(
            model_name='onlinepayment',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='دیتای ارسالی به درگاه'),
        ),
        migrations.AlterField(
            model_name='onlinepayment',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_gateway.gateway', verbose_name='درگاه'),
        ),
        migrations.AlterField(
            model_name='onlinepayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='onlinepayment',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket.basket', verbose_name='سبد خرید پرداختی'),
        ),
        migrations.AlterField(
            model_name='onlinepayment',
            name='ref_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='کد رهگیری خرید'),
        ),
        migrations.AlterField(
            model_name='onlinepayment',
            name='response',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='دیتای دریافتی از درگاه'),
        ),
        migrations.AlterField(
            model_name='onlinepayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
