# Generated by Django 3.2.12 on 2023-10-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0002_auto_20231021_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='code',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='onlinepayment',
            name='failed_cause',
        ),
        migrations.RemoveField(
            model_name='onlinepayment',
            name='failed_code',
        ),
        migrations.AddField(
            model_name='gateway',
            name='name',
            field=models.CharField(choices=[('BMI', 'ملی'), ('SEP', 'SEP'), ('ZARINPAL', 'زرین پال'), ('IDPAY', 'آیدی پی'), ('MELLAT', 'ملت'), ('ZIBAL', 'زیبال'), ('BAHAMTA', 'با همتا'), ('PAYV1', 'PAYV1')], default='IDPAY', max_length=10),
            preserve_default=False,
        ),
    ]
