# Generated by Django 3.2.12 on 2024-01-20 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0013_auto_20240119_0414'),
        ('payment_gateway', '0002_auto_20231113_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepayment',
            name='closed_basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket.closedbasket', verbose_name='سبد خرید بسته شده'),
        ),
    ]
