# Generated by Django 3.2.12 on 2023-10-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0003_auto_20231023_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='gateway',
            field=models.CharField(choices=[('BMI', 'ملی'), ('SEP', 'SEP'), ('ZARINPAL', 'زرین پال'), ('IDPAY', 'آیدی پی'), ('MELLAT', 'ملت'), ('ZIBAL', 'زیبال'), ('BAHAMTA', 'با همتا'), ('PAYV1', 'PAYV1')], default='زرین 1', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gateway',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
