# Generated by Django 3.2.12 on 2023-10-23 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0014_auto_20231021_1916'),
        ('payment_gateway', '0004_auto_20231023_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinepayment',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket.basket'),
        ),
    ]
