# Generated by Django 3.2.12 on 2023-10-23 19:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0007_alter_onlinepayment_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinepayment',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='توکن'),
        ),
    ]
