# Generated by Django 3.2.12 on 2023-10-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0008_alter_onlinepayment_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
