# Generated by Django 3.2.12 on 2023-09-28 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_alter_basket_product'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basket.basket'),
        ),
    ]
