# Generated by Django 3.2.12 on 2023-11-13 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_auto_20231113_1854'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0007_rename_closed_basket_payment_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت ها'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basket.closedbasket', verbose_name='سبد خرید'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_price_with_offer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت کل با تخفیف'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
