# Generated by Django 3.2.12 on 2024-01-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20231113_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
