# Generated by Django 3.2.12 on 2024-01-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_payment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_price_with_offer',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='قیمت کل با تخفیف'),
        ),
    ]
