# Generated by Django 3.2.12 on 2023-11-05 22:45

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_alter_business_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('percent', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('expire_date', models.DateTimeField()),
                ('maximum_offer_price', models.PositiveIntegerField(blank=True, null=True)),
                ('limited_businesses', models.ManyToManyField(blank=True, to='business.Business')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offer',
            },
        ),
    ]
