# Generated by Django 3.2.12 on 2023-11-13 15:24

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20231113_1854'),
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'کد تخفیف سبد خرید', 'verbose_name_plural': 'کد تخفیف های سبد خرید'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='expire_date',
            field=models.DateTimeField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='limited_businesses',
            field=models.ManyToManyField(blank=True, to='business.Business', verbose_name='کسب و کار ها'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='maximum_offer_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر مقدار تخفیف'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_code',
            field=models.CharField(db_index=True, max_length=16, unique=True, verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='percent',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='تاریخ شروع'),
        ),
    ]
