# Generated by Django 3.2.12 on 2023-09-04 22:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('count', models.PositiveSmallIntegerField()),
                ('payment_price', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_offer_percent', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('payment_price_with_offer', models.PositiveIntegerField(blank=True, null=True)),
                ('total_price', models.PositiveIntegerField(blank=True, null=True)),
                ('total_price_with_offer', models.PositiveIntegerField(blank=True, null=True)),
                ('line_coupon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coupon.linecoupon')),
            ],
            options={
                'verbose_name': 'Basket Detail',
                'verbose_name_plural': 'Basket Details',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('count', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('total_price', models.PositiveIntegerField(blank=True, null=True)),
                ('total_offer_percent', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('total_price_with_offer', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ManyToManyField(blank=True, null=True, to='basket.BasketDetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Basket',
                'verbose_name_plural': 'Baskets',
            },
        ),
    ]
