# Generated by Django 3.2.12 on 2023-09-02 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketdetail',
            name='line_coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coupon.linecoupon'),
        ),
        migrations.AddField(
            model_name='basket',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='basket.BasketDetail'),
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
