# Generated by Django 3.2.12 on 2023-08-28 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='count',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='basketdetail',
            name='count',
            field=models.SmallIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
