# Generated by Django 3.2.12 on 2023-09-28 10:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0010_auto_20230911_1554'),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closedbasketdetail',
            options={'verbose_name': 'Closed Basket Detail', 'verbose_name_plural': 'Closed Basket Details'},
        ),
        migrations.AddField(
            model_name='closedbasketdetail',
            name='count',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closedbasketdetail',
            name='line_coupon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='coupon.linecoupon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closedbasketdetail',
            name='payment_offer_percent',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='closedbasketdetail',
            name='payment_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='closedbasketdetail',
            name='payment_price_with_offer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='closedbasketdetail',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='closedbasketdetail',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='closedbasketdetail',
            name='total_price_with_offer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
