# Generated by Django 3.2.12 on 2023-08-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_auto_20230829_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='basket.BasketDetail'),
        ),
    ]
