# Generated by Django 3.2.12 on 2023-09-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_alter_basket_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='product',
            field=models.ManyToManyField(to='basket.BasketDetail'),
        ),
    ]
