# Generated by Django 3.2.12 on 2023-09-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_auto_20230928_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketdetail',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='closedbasketdetail',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=128, null=True, unique=True),
        ),
    ]
