# Generated by Django 3.2.12 on 2023-09-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketdetail',
            old_name='final_price',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='basketdetail',
            old_name='final_price_with_offer',
            new_name='total_price_with_offer',
        ),
    ]
