# Generated by Django 3.2.12 on 2023-08-29 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_alter_basket_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='total_offer',
            new_name='total_offer_price',
        ),
        migrations.RenameField(
            model_name='basketdetail',
            old_name='payment_offer',
            new_name='payment_offer_price',
        ),
    ]
