# Generated by Django 3.2.12 on 2023-09-28 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_auto_20230929_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='product',
            field=models.ManyToManyField(blank=True, db_constraint=django.db.models.deletion.CASCADE, null=True, to='basket.BasketDetail'),
        ),
    ]
