# Generated by Django 3.2.12 on 2023-08-30 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_auto_20230830_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketdetail',
            name='rate',
        ),
    ]
