# Generated by Django 3.2.12 on 2023-10-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_alter_basket_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[(1, 'Not Paid'), (2, 'Not Verified'), (3, 'Verified'), (4, 'Failed')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='closedbasket',
            name='status',
            field=models.CharField(choices=[(1, 'Not Paid'), (2, 'Not Verified'), (3, 'Verified'), (4, 'Failed')], default=1, max_length=1),
        ),
    ]
