# Generated by Django 3.2.12 on 2023-11-10 18:33

from django.db import migrations, models
import django.db.models.deletion
import src.basket.models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0011_remove_category_level'),
        ('basket', '0005_alter_basket_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Created'), (2, 'Paid'), (3, 'Verified'), (4, 'Canceled')], default=1),
        ),
        migrations.AddField(
            model_name='closedbasket',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Created'), (2, 'Paid'), (3, 'Verified'), (4, 'Canceled')], default=1),
        ),
        migrations.AddField(
            model_name='closedbasketdetail',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Created'), (2, 'Verified'), (3, 'Canceled')], default=1),
        ),
        migrations.CreateModel(
            name='ProductValidationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, default=src.basket.models.generate_random_string, max_length=128, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('closed_basket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket.closedbasket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.linecoupon')),
            ],
            options={
                'verbose_name': 'Coupon Code',
                'verbose_name_plural': 'Coupon Codes',
            },
        ),
    ]
