# Generated by Django 3.2.12 on 2023-08-30 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_remove_basketdetail_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='total_offer_price',
        ),
        migrations.RemoveField(
            model_name='basketdetail',
            name='final_offer_price',
        ),
        migrations.RemoveField(
            model_name='basketdetail',
            name='payment_offer_price',
        ),
        migrations.AddField(
            model_name='basket',
            name='total_offer_percent',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='basketdetail',
            name='payment_offer_percent',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='basket',
            name='count',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='basket',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='total_price_with_offer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketdetail',
            name='count',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='basketdetail',
            name='final_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketdetail',
            name='final_price_with_offer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketdetail',
            name='payment_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
