# Generated by Django 3.2.12 on 2023-11-13 15:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import src.basket.models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0012_auto_20231113_1854'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basket', '0006_auto_20231110_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبد خرید ها'},
        ),
        migrations.AlterModelOptions(
            name='basketdetail',
            options={'verbose_name': 'محصول سبد خرید', 'verbose_name_plural': 'محصولات سبد خرید'},
        ),
        migrations.AlterModelOptions(
            name='closedbasket',
            options={'verbose_name': 'سبد خرید بسته شده', 'verbose_name_plural': 'سبد خرید های بسته شده'},
        ),
        migrations.AlterModelOptions(
            name='closedbasketdetail',
            options={'verbose_name': 'محصول سبد خرید بسته شده', 'verbose_name_plural': 'محصولات سبد خرید بسته شده'},
        ),
        migrations.AlterModelOptions(
            name='productvalidationcode',
            options={'verbose_name': 'کد تخفیف لاین کوپن', 'verbose_name_plural': 'کد تخفیف های لاین کوپن'},
        ),
        migrations.AlterField(
            model_name='basket',
            name='count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد سبد خرید'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده / نشده'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='payment_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت سبد خرید'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='basket.BasketDetail', verbose_name='محصولات'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'ایجاد شده'), (2, 'پرداخت شده'), (3, 'تایید شده'), (4, 'لغو شده')], default=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='total_offer_percent',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف کل'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='total_price_with_offer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت کل با تخفیف'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='basketdetail',
            name='count',
            field=models.PositiveSmallIntegerField(verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='basketdetail',
            name='line_coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.linecoupon', verbose_name='لاین کوپن'),
        ),
        migrations.AlterField(
            model_name='basketdetail',
            name='payment_offer_percent',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف تمام شده'),
        ),
        migrations.AlterField(
            model_name='basketdetail',
            name='payment_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت تمام شده'),
        ),
        migrations.AlterField(
            model_name='basketdetail',
            name='payment_price_with_offer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت تمام شده با تخفیف'),
        ),
        migrations.AlterField(
            model_name='basketdetail',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='basketdetail',
            name='total_price_with_offer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت کل با تخفیف'),
        ),
        migrations.AlterField(
            model_name='closedbasket',
            name='count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='closedbasket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد سبد خرید'),
        ),
        migrations.AlterField(
            model_name='closedbasket',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده / نشده'),
        ),
        migrations.AlterField(
            model_name='closedbasket',
            name='payment_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت سبد خرید'),
        ),
        migrations.AlterField(
            model_name='closedbasket',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='basket.ClosedBasketDetail', verbose_name='محصولات'),
        ),
        migrations.AlterField(
            model_name='closedbasket',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'ایجاد شده'), (2, 'پرداخت شده'), (3, 'تایید شده'), (4, 'لغو شده')], default=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='closedbasket',
            name='total_offer_percent',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف کل'),
        ),
        migrations.AlterField(
            model_name='closedbasket',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='closedbasket',
            name='total_price_with_offer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت کل با تخفیف'),
        ),
        migrations.AlterField(
            model_name='closedbasket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='closedbasketdetail',
            name='count',
            field=models.PositiveSmallIntegerField(verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='closedbasketdetail',
            name='line_coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.linecoupon', verbose_name='لاین کوپن'),
        ),
        migrations.AlterField(
            model_name='closedbasketdetail',
            name='payment_offer_percent',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف تمام شده'),
        ),
        migrations.AlterField(
            model_name='closedbasketdetail',
            name='payment_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت تمام شده'),
        ),
        migrations.AlterField(
            model_name='closedbasketdetail',
            name='payment_price_with_offer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت تمام شده با تخفیف'),
        ),
        migrations.AlterField(
            model_name='closedbasketdetail',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'ایجاد شده'), (2, 'تایید شده'), (3, 'لغو شده')], default=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='closedbasketdetail',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='closedbasketdetail',
            name='total_price_with_offer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت کل با تخفیف'),
        ),
        migrations.AlterField(
            model_name='productvalidationcode',
            name='closed_basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket.closedbasket', verbose_name='سبد خرید بسته شده'),
        ),
        migrations.AlterField(
            model_name='productvalidationcode',
            name='code',
            field=models.CharField(blank=True, db_index=True, default=src.basket.models.generate_random_string, max_length=128, unique=True, verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='productvalidationcode',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.linecoupon', verbose_name='لاین کوپن'),
        ),
        migrations.AlterField(
            model_name='productvalidationcode',
            name='used',
            field=models.BooleanField(default=False, verbose_name='استفاده شده / نشده'),
        ),
    ]
