# Generated by Django 3.2.12 on 2023-10-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_auto_20231011_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[(1, 'Created'), (2, 'Paid'), (3, 'Verified'), (4, 'Canceled')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='closedbasket',
            name='status',
            field=models.CharField(choices=[(1, 'Created'), (2, 'Paid'), (3, 'Verified'), (4, 'Canceled')], default=1, max_length=1),
        ),
    ]
