# Generated by Django 3.2.12 on 2023-09-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_auto_20230830_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketdetail',
            name='count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
