# Generated by Django 3.2.12 on 2023-08-30 22:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_auto_20230830_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='basket',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='basketdetail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
