# Generated by Django 3.2.12 on 2024-01-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_auto_20231113_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='payer_user',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='پرداخت کننده'),
        ),
        migrations.AddField(
            model_name='closedbasket',
            name='payer_user',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='پرداخت کننده'),
        ),
    ]
