# Generated by Django 3.2.12 on 2023-10-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_auto_20231011_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedbasketdetail',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Created'), (2, 'Verified'), (3, 'Canceled')], default=1),
        ),
    ]
