# Generated by Django 3.2.12 on 2024-01-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_auto_20240114_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='status',
        ),
        migrations.AlterField(
            model_name='closedbasket',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'ایجاد شده'), (2, 'پرداخت شده'), (3, 'تایید شده'), (4, 'لغو شده')], default=2, verbose_name='وضعیت'),
        ),
    ]
