# Generated by Django 3.2.12 on 2024-01-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_auto_20240107_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='payer_user',
        ),
        migrations.RemoveField(
            model_name='closedbasket',
            name='payer_user',
        ),
        migrations.AddField(
            model_name='basket',
            name='gifted',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='هدیه به'),
        ),
        migrations.AddField(
            model_name='closedbasket',
            name='gifted',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='هدیه به'),
        ),
    ]
