# Generated by Django 3.2.12 on 2023-10-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_closedbasketdetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Created'), (2, 'Paid'), (3, 'Verified'), (4, 'Canceled')], default=1),
        ),
        migrations.AlterField(
            model_name='closedbasket',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Created'), (2, 'Paid'), (3, 'Verified'), (4, 'Canceled')], default=1),
        ),
        migrations.AlterField(
            model_name='closedbasketdetail',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Created'), (2, 'Verified'), (3, 'Canceled')], default=1),
        ),
    ]
