# Generated by Django 3.2.12 on 2024-01-13 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_auto_20240107_1610'),
        ('basket', '0009_auto_20240114_0044'),
    ]

    operations = [
    ]
