# Generated by Django 3.2.12 on 2023-10-16 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0010_auto_20231012_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductValidationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.closedbasketdetail')),
            ],
        ),
    ]
