# Generated by Django 3.2.12 on 2023-08-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0010_alter_basket_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
