# Generated by Django 3.2.12 on 2024-01-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0010_merge_0009_auto_20240107_1610_0009_auto_20240114_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketdetail',
            options={'ordering': ['slug'], 'verbose_name': 'محصول سبد خرید', 'verbose_name_plural': 'محصولات سبد خرید'},
        ),
        migrations.AlterField(
            model_name='basket',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='basketdetail',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=128, null=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='closedbasket',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='closedbasketdetail',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=128, null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
