# Generated by Django 3.2.12 on 2023-10-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0011_productvalidationcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvalidationcode',
            options={'verbose_name': 'Coupon Code', 'verbose_name_plural': 'Coupon Codes'},
        ),
        migrations.AlterField(
            model_name='productvalidationcode',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
