# Generated by Django 3.2.12 on 2024-01-17 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0011_auto_20240117_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='total_offer_percent',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف کل'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='total_price_with_offer',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='قیمت کل با تخفیف'),
        ),
        migrations.AlterField(
            model_name='basketdetail',
            name='payment_offer_percent',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف تمام شده'),
        ),
        migrations.AlterField(
            model_name='basketdetail',
            name='payment_price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='قیمت تمام شده'),
        ),
        migrations.AlterField(
            model_name='basketdetail',
            name='payment_price_with_offer',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='قیمت تمام شده با تخفیف'),
        ),
        migrations.AlterField(
            model_name='basketdetail',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='basketdetail',
            name='total_price_with_offer',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='قیمت کل با تخفیف'),
        ),
        migrations.AlterField(
            model_name='closedbasket',
            name='count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='closedbasket',
            name='total_offer_percent',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف کل'),
        ),
        migrations.AlterField(
            model_name='closedbasket',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='closedbasket',
            name='total_price_with_offer',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='قیمت کل با تخفیف'),
        ),
        migrations.AlterField(
            model_name='closedbasketdetail',
            name='payment_offer_percent',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف تمام شده'),
        ),
        migrations.AlterField(
            model_name='closedbasketdetail',
            name='payment_price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='قیمت تمام شده'),
        ),
        migrations.AlterField(
            model_name='closedbasketdetail',
            name='payment_price_with_offer',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='قیمت تمام شده با تخفیف'),
        ),
        migrations.AlterField(
            model_name='closedbasketdetail',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='closedbasketdetail',
            name='total_price_with_offer',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='قیمت کل با تخفیف'),
        ),
    ]
