# Generated by Django 3.2.12 on 2023-08-30 22:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0011_alter_basket_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
