# Generated by Django 3.2.12 on 2023-10-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0012_auto_20231017_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvalidationcode',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
