# Generated by Django 3.2.12 on 2023-08-30 23:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0012_alter_basket_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
