# Generated by Django 3.2.12 on 2024-01-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0012_auto_20240117_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedbasket',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'ایجاد شده'), (2, 'پرداخت شده'), (3, 'تایید شده'), (4, 'لغو شده')], default=3, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='closedbasketdetail',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'ایجاد شده'), (2, 'تایید شده'), (3, 'لغو شده')], default=2, verbose_name='وضعیت'),
        ),
    ]
