# Generated by Django 3.2.12 on 2024-01-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0013_auto_20240119_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='basket_offer_percent',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='تخفیف سبد خرید'),
        ),
        migrations.AddField(
            model_name='basket',
            name='basket_offer_price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='قیمت تخفیف سبد خرید'),
        ),
        migrations.AddField(
            model_name='closedbasket',
            name='basket_offer_percent',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='تخفیف سبد خرید'),
        ),
        migrations.AddField(
            model_name='closedbasket',
            name='basket_offer_price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='قیمت تخفیف سبد خرید'),
        ),
    ]
