# Generated by Django 3.2.12 on 2023-10-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0013_productvalidationcode_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='status',
        ),
        migrations.RemoveField(
            model_name='closedbasket',
            name='status',
        ),
        migrations.RemoveField(
            model_name='closedbasketdetail',
            name='status',
        ),
        migrations.DeleteModel(
            name='ProductValidationCode',
        ),
    ]
