# Generated by Django 3.2.12 on 2024-02-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0014_auto_20240122_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketdetail',
            name='total_commission',
            field=models.PositiveIntegerField(default=0, verbose_name='پورسانت کل'),
        ),
        migrations.AddField(
            model_name='closedbasketdetail',
            name='total_commission',
            field=models.PositiveIntegerField(default=0, verbose_name='پورسانت کل'),
        ),
    ]
