# Generated by Django 3.2.12 on 2023-10-25 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0014_auto_20231021_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Created'), (2, 'Paid'), (3, 'Verified'), (4, 'Canceled')], default=1),
        ),
        migrations.AddField(
            model_name='closedbasket',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Created'), (2, 'Paid'), (3, 'Verified'), (4, 'Canceled')], default=1),
        ),
        migrations.AddField(
            model_name='closedbasketdetail',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Created'), (2, 'Verified'), (3, 'Canceled')], default=1),
        ),
        migrations.CreateModel(
            name='ProductValidationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.closedbasketdetail')),
            ],
            options={
                'verbose_name': 'Coupon Code',
                'verbose_name_plural': 'Coupon Codes',
            },
        ),
    ]
