# Generated by Django 3.2.12 on 2023-11-13 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'حساب', 'verbose_name_plural': 'حساب\u200c ها'},
        ),
        migrations.AlterModelOptions(
            name='requestsettlement',
            options={'verbose_name': 'درخواست تسویه', 'verbose_name_plural': 'درخواست های تسویه'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'تراکنش', 'verbose_name_plural': 'تراکنش\u200c ها'},
        ),
        migrations.AlterModelOptions(
            name='turnover',
            options={'verbose_name': 'گردش حساب', 'verbose_name_plural': 'گردش حساب ها'},
        ),
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ضاحب حساب'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
