# Generated by Django 3.2.12 on 2024-01-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20240102_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestsettlement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='turnover',
            name='account',
        ),
        migrations.RemoveField(
            model_name='turnover',
            name='transaction',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'در انتظار تایید'), (2, 'موفق'), (3, 'ناموفق')], default=1, verbose_name='وضعیت'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='RequestSettlement',
        ),
        migrations.DeleteModel(
            name='Turnover',
        ),
    ]
