# Generated by Django 3.2.12 on 2024-01-15 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0018_auto_20240114_0257'),
        ('basket', '0010_merge_0009_auto_20240107_1610_0009_auto_20240114_0044'),
        ('wallet', '0004_auto_20240103_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='closed_basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basket.closedbasket', verbose_name='سبد خرید'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon', verbose_name='کوپن'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='line_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coupon.linecoupon', verbose_name='لاین کوپن'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='price_with_out_offer',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='مبلغ بدون نخفیف'),
        ),
    ]
