# Generated by Django 3.2.12 on 2024-01-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20240115_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'تراکنش', 'verbose_name_plural': 'تراکنش ها'},
        ),
    ]
