# Generated by Django 3.2.12 on 2024-02-03 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0006_alter_transaction_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='price_with_out_offer',
            new_name='price_without_offer',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='خریدار'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'در انتظار تایید'), (2, 'موفق'), (3, 'ناموفق')], default=2, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کسب و کار'),
        ),
    ]
