# Generated by Django 3.2.12 on 2024-02-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_auto_20240204_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='commission',
            field=models.PositiveIntegerField(default=0, verbose_name='پورسانت کل'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='final_amount',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='مبلغ با احتساب پورسانت'),
        ),
    ]
