# Generated by Django 3.2.12 on 2024-02-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_auto_20240229_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='final_amount',
        ),
    ]
